apiVersion: v1
kind: Service
metadata:
  name: hello-world-nextjs
spec:
  selector:
    app: hello-world-nextjs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080  # Adjust to the port your application is running on
  type: LoadBalancer

